image: atlassian/default-image:3

pipelines:
  branches:
    dev:
    - step:
        name: "Git pull, docker-compose"
        deployment: staging
        script:
          - pipe: atlassian/ssh-run:0.4.0
            variables:
              SSH_USER: $SSH_USER
              SERVER: $SSH_SERVER
              COMMAND: >
                cd $DIR &&
                git fetch &&
                git checkout dev &&
                git pull
                cd $DIR/monday &&
                docker-compose up --build -d                