image: atlassian/default-image:3

pipelines:
  branches:
    dev:
    - step:
        name: "Git pull, docker-compose on DEV"
        deployment: staging
        script:
          - pipe: atlassian/ssh-run:0.4.0
            variables:
              SSH_USER: $SSH_USER
              SERVER: $SSH_SERVER
              COMMAND: >
                echo "env: "$BITBUCKET_DEPLOYMENT_ENVIRONMENT &&
                echo "env uuid: "$BITBUCKET_DEPLOYMENT_ENVIRONMENT_UUID &&
                cd $DIR &&
                git fetch &&
                git checkout dev &&
                git pull &&
                cd $DIR/monday &&
                docker-compose up --build -d
    master:
    - step:
        name: "Git pull, docker-compose on MASTER"
        deployment: production
        script:
          - pipe: atlassian/ssh-run:0.4.0
            variables:
              SSH_USER: $SSH_USER
              SERVER: $SSH_SERVER
              COMMAND: >
                echo "env: "$BITBUCKET_DEPLOYMENT_ENVIRONMENT &&
                echo "env uuid: "$BITBUCKET_DEPLOYMENT_ENVIRONMENT_UUID &&
                cd $DIR &&
                git fetch &&
                git checkout dev &&
                git pull &&
                cd $DIR/monday &&
                docker-compose up --build -d