#image: atlassian/default-image:3
image: node:14.17.0

pipelines:
  branches:
    dev:
    - step:
        name: "Git pull, docker-compose on staging"
        deployment: staging
        script:
          - pipe: atlassian/ssh-run:0.4.0
            variables:
              SSH_USER: $SSH_USER
              SERVER: $SSH_SERVER
              COMMAND: >
                echo "env: "$BITBUCKET_DEPLOYMENT_ENVIRONMENT &&
                echo "env uuid: "$BITBUCKET_DEPLOYMENT_ENVIRONMENT_UUID &&
                cd $DIR &&
                git fetch &&
                git checkout dev &&
                git pull &&
                cd $DIR/monday &&
                docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD &&
                docker build ./app -t $IMAGE_NAME:dev &&
                docker push $IMAGE_NAME:dev &&
                docker logout &&
                docker-compose up -d
    master:
    - step:
        name: "build step"
        services:
          - docker
        script:
          - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
          - docker build -t $IMAGE_NAME:production ./monday/app/
          - docker push $IMAGE_NAME:production
    - step:
        name: "Git pull on production"
        deployment: production
        script:
          - pipe: atlassian/ssh-run:0.4.0
            variables:
              SSH_USER: $SSH_USER
              SERVER: $SSH_SERVER
              COMMAND: >
                echo "env: "$BITBUCKET_DEPLOYMENT_ENVIRONMENT &&
                echo "env uuid: "$BITBUCKET_DEPLOYMENT_ENVIRONMENT_UUID &&
                cd $DIR &&
                git fetch &&
                git checkout master &&
                git pull &&
                cd $DIR/monday &&
                docker-compose -f docker-compose.production.yaml up -d