image: atlassian/default-image:3

pipelines:
  branches:
    dev:
    - step:
        name: "Git fetch and pull dev branch"
        script:
          - pipe: atlassian/ssh-run:0.4.0
            variables:
              SSH_USER: 'root'
              SERVER: '82.148.16.91'
              COMMAND: >
                cd ~/devops-test &&
                git fetch &&
                git checkout dev &&
                git pull
