version: '3.5'
services:
  app-review:
    #build: app/
    command: node ./app.js
    ports:
     - 3000:3000
    # should be the same as in bitbucket-pipelines.yml
    image: ergrassa/devops-test-app:staging
    environment:
     - VIRTUAL_HOST=review.badger.local
     - VIRTUAL_PORT=3000
    volumes:
      - ./data:/var/www/html/data:rw
    networks:
      backend:
      proxynet:
        aliases:
          - app-review
#        ipv4_address: 172.16.238.2

networks:
  proxynet:
    name: proxynet
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  backend:
    name: backend
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

