version: '3.5'
services:
  app-feature:
    #build: app/
    command: node ./app.js
#    ports:
#     - 4000:3000
    # should be the same as in bitbucket-pipelines.yml
    image: ergrassa/devops-test-app:review
    environment:
     - VIRTUAL_HOST=$APPNAME.app
     - VIRTUAL_PORT=4000
    volumes:
      - ./data:/var/www/html/data:rw
    networks:
#      backend:
      proxynet:
        aliases:
          - $APPNAME
          - app-review-$APPNAME
#        ipv4_address: 172.16.238.2

networks:
  proxynet:
    name: proxynet
    driver: bridge
