version: '3.5'
services:
  app-review:
    #build: app/
    command: node ./app.js
#    ports:
#     - 4000:3000
    expose:
      - "3000"
    # should be the same as in bitbucket-pipelines.yml
    image: ergrassa/devops-test-app:_feature_
    environment:
     - VIRTUAL_HOST=_feature_
#     - VIRTUAL_PORT=4000
    # volumes:
    #   - ./data:/var/www/html/data:rw
    networks:
      net-_feature_:
        aliases:
          - app-review-_feature_
#        ipv4_address: 172.16.238.2

networks:
  net-_feature_:
    name: net-_feature_
    external: true

