version: '3.5'
services:
  app-review:
    #build: app/
    command: node ./app.js
    ports:
     - 4000:3000
    # should be the same as in bitbucket-pipelines.yml
    image: ergrassa/devops-test-app:feature-brave
    environment:
     - VIRTUAL_HOST=feature-brave
#     - VIRTUAL_PORT=4000
    # volumes:
    #   - ./data:/var/www/html/data:rw
    networks:
      net-feature-brave:
        aliases:
          - app-review-feature-brave
#        ipv4_address: 172.16.238.2

networks:
  net-feature-brave:
    name: net-feature-brave
    external: true

