version: '3.5'
services:
  app-review:
    #build: app/
    command: node ./app.js
    # ports:
    #  - 4000:3000
    # should be the same as in bitbucket-pipelines.yml
    image: ergrassa/devops-test-app:feature
    environment:
     - VIRTUAL_HOST=feature
     - VIRTUAL_PORT=4000
#    volumes:
#      - ./data:/var/www/html/data:rw
    networks:
      backend:
      proxynet:
        aliases:
          - app-review-feature
#        ipv4_address: 172.16.238.2

networks:
  proxynet:
    name: proxynet
  backend:
    name: backend

