# This is a basic workflow to help you get started with Actions

name: Get branch name and test

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  branchname:
    runs-on: ubuntu-latest
    outputs:
      feature: ${{ steps.extract_branch.outputs.feature }}
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
    - 
      name: Extract branch name
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo ${GITHUB_REF#refs/heads/}
        echo "##[set-output name=feature;]$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/')"
        echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/'
      id: extract_branch
      
  echo:
    needs: branchname
    runs-on: ubuntu-latest
    steps:
    -
      name: echo
      env:
        NET_PREFIX: lms # префикс сети
        T_FEATURE: _feature_ # строка поиска в шаблоне для замены на feature-name
        T_BRANCH: _branch_ # строка поиска в шаблоне для замены на feature/name
        FEATURE: ${{ needs.branchname.outputs.feature }} # feature-name
        BRANCH: ${{ needs.branchname.outputs.branch }} # feature/name
      shell: bash
      run: |
        echo ${{ NET_PREFIX }}
        echo ${{ env.T_FEATURE }}
        echo ${{ T_BRANCH }}
        echo ${{ env.FEATURE }}
        echo ${{ env.BRANCH }}
