# This is a basic workflow to help you get started with Actions

name: Get branch name and test

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  branchname:
  runs-on: ubuntu-latest
    steps:
    - 
      name: Extract branch name
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo ${GITHUB_REF#refs/heads/}
        echo "##[set-output name=feature;]$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/')"
        echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/'
      id: extract_branch
