name: Build and Update Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  IMAGE_NAME: ergrassa/devops-test-app
  PROJECT_PATH: /home/coyote/devops-test/monday
jobs:
  build:
    environment: production
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      #SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2    
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      uses: docker/login-action@v1
      name: Dockerhub login
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - 
      uses: docker/build-push-action@v2
      name: Build and push dockerimage
      with:
        context: ./monday/app
        push: true
        tags: ${{ env.IMAGE_NAME }}:production
        file: ./monday/app/Dockerfile
   
    -
      name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ env.SSH_KEY }}
        username: ${{ env.SSH_USER }}
        #key: ${{ secrets.PROD_KEY }}
        password: ${{ env.SSH_PASSWORD }}
        script: |
          cd /home/coyote/devops-test
          git checkout master          
          git fetch
          git pull
          docker pull ${{ env.IMAGE_NAME }}:production
          cd ${{ env.PROJECT_PATH }}
          docker-compose -f docker-compose.production.yaml up -d
