name: Build and Update

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
env:
  IMAGE_NAME: ergrassa/devops-test
  PROJECT_PATH: /root/devops-test/monday
jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    steps:
    -
      uses: docker/login-action@v1
      name: Dockerhub login
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - 
      uses: docker/build-push-action@v2
      name: Build and push dockerimage
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}:staging
        file: ./monday/app/Dockerfile
   
    -
      name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USERNAME }}
        key: ${{ secrets.STAGING_KEY }}
        script: |
          cd /root/devops-test
          git checkout dev            
          git fetch
          git pull
          cd ${{ env.PROJECT_PATH }}
          docker-compose -f docker-compose.staging.yaml up -d
