name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: docker/login-action@v1
      name: Dockerhub login
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - 
      uses: docker/build-push-action@v2
      name: Build and push dockerimage
      with:
        push: true
        tags: ergrassa/devops-test-app:staging
        dockerfile: ./monday/app/Dockerfile
    #  run: docker build ./monday/app/ --file Dockerfile --tag my-image-name:$(date +%s)
    # run: docker build -t ergrassa/devops-test-app:staging ./monday/app/