name: Shut Down Review App
on:
  delete:
   branches:
    - feature/*
jobs:
  shut-down-review:
    environment: staging
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    name: Shut-Down-Review-Cleanup
    runs-on: ubuntu-latest
    steps:
    - 
      name: Extract branch name
      shell: bash
      run: |
        echo "##[set-output name=feature;]$(echo ${{ github.event.ref }} | sed 's/\//-/')"
        echo ${{ github.event.ref }} | sed 's/\//-/'

      id: extract_branch
    -
      name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        script: |
          echo ${{ steps.extract_branch.outputs.feature }}
          cd ~/devops-test/monday/review
          docker-compose -f ./${{ steps.extract_branch.outputs.feature }}/docker-compose.review.yaml down --volumes --remove-orphans --rmi all
          docker network disconnect net-${{ steps.extract_branch.outputs.feature }} nginx-proxy-ngp-1
          docker network rm net-${{ steps.extract_branch.outputs.feature }}
          rm -r ./${{ steps.extract_branch.outputs.feature }}